### PR TITLE
Add live event for raw_ids lookup and Show button on image_gallery te…

### PR DESCRIPTION
**Pull request by dbarakh**
…mplate.
I don't see other plugins with the same issue so I put the js code directly in the template. The template extends the django admin one which we can't edit.

### CODE REVIEW

**Comment by cogat** [comment]
Any plugin will have the same issues - it's just that the "(show)" is only used in this plugin (but we want to use it in more plugins) and the raw_id is patched for django-fluent-pages(?) models in the commit I referred to in the assembla ticket. Where should we make changes that apply to all django-fluent-contents models?

Also, can we re-use the existing (django?) code that makes the "(show)" function work, rather than reimplementing?

**Comment by forrytoo** [comment]
Yes, I think we can just amend `django/contrib/admin/static/admin/js/collapse.js` or create a new file which will replace django one. 
All we need is replacing `$("fieldset.collapse a.collapse-toggle").click(function(ev) {` (13 line) with `$(document).on('click', "fieldset.collapse a.collapse-toggle", function(ev) {`
In this case we will avoid of the hack in `slideshow/admin/change_form.html` (the second `on()` function)
Please, don't forget about `collapse.min.js`

**Comment by mrmachine** [comment]
@forrytoo instead of overriding Django admin JS files (which could make upgrading Django harder), is there another way we can extend or patch the Django code from a new file (that doesn't override any Django file) that we include on every page or every page that needs it?

**Comment by dbarakh** [comment]
@mrmachine Yes, we can create a new file. Then we make a new class based on `PlaceholderFieldAdmin` (to avoid direct editing the class in `fluent_contents` library) and add file in self.Media.js in its __init__ method.

**Comment by cogat** [comment]
In the end @jmurty tracked down the right place and committed a patch to fluent-contents (which I can't find right now). Closing this one.

**Comment by jmurty** [comment]
See #138

**Pull request closed without merging**
